[metadata]
name = "In-Store Transactions"
description = "This FRED model has all agents 18 and older go shopping. The number of stores, items available, and item prices are specified in data/item_inventory_TRANSACTIONS.csv. The job will print out receipts as agents shop at their chosen stores."
categories = [
    "Infrastructure"
]
authors = [
    "Erin Zwick"
]
version = "0.1.0"
fred_versions = [
  ">=8.4",
  "<9"
]

[run_options]
src_dir = "source"
entrypoint = "main_transactions.fred"
