[metadata]
name = "Schelling Housing Model"
description = """
The Schelling model of racial segregation in housing. This is a classic ABM
that demonstrates how even slight preferences among a population for living
next to others who are similar to themselves can lead to highly segregated
neighborhoods."""
categories = [
    "Social Science",
    "Policy Analysis"
]
authors = [
    "Claire Dickey <claire.dickey@epistemix.com>"
]
version = "0.1.0"
fred_versions = [
  ">=8.4",
  "<9"
]

[run_options]
src_dir = "source"
entrypoint = "model/schelling_block.fred"