[metadata]
name = "Water Usage"
description = "The objective of the water usage app model is to simulate household water use. We assume there are 5 main water use activities: watering the lawn, showering, cleaning, eating, and using the toilet. The model has two components: an activity component that describes how much water households use based on the household composition of adults and children and a reporting component. The model prints a csv of household usage grouped by block group."
categories = [
    "Infrastructure"
]
authors = [
    "Paige Miller, Noah Burrell"
]
version = "0.1.0"
fred_versions = [
  ">=8.4",
  "<9"
]
banner = "./images/light_blue_epistemix.png"

[run_options]
src_dir = "source"
entrypoint = "model/main_WATER.fred"
