[metadata]
name = "Misinformation Model"
description = "This model builds a network to represent day-to-day in-person interactions between agents. It then has agents share an idea, which is represented by an (x,y) coordinate pair. Each idea originator starts with idea values of (0,0) but with act of sharing, a small amount of noise is added to the values received by the agents being told. As the idea is shared through the network, it rapidly evolves away from its starting values."
categories = [
    "Social Science"
]
authors = [
    "Claire Dickey <claire.dickey@epistemix.com>"
]
version = "0.1.0"
fred_versions = [
  ">=11.0.1"
]
banner = "./images/lime_epistemix.png"

[run_options]
src_dir = "source"
entrypoint = "model/main.fred"
