[metadata]
name = "Asthma Events"
description = "A model that gives some agents an asthma attribute, and triggers asthma events based on the input daily air quality (AQI)."
categories = [
    "Epidemiology"
]
authors = [
    "Claire Dickey <claire.dickey@epistemix.com>"
]
version = "0.2.0"
fred_versions = [
    ">=10.1.0",
    "<11"
]
banner = "./images/black_epistemix.png"
[run_options]
src_dir = "model/"
entrypoint = "main.fred"
