[metadata]
name = "Finding a Local Doctor"
description = """
This model explores the effect of modernisation of healthcare services on healthcare outcomes. At the individual level the model tracks personal health changes over time. Ideally, when patients become sick they try to access their local GP to resolve moderate health issues. For severe cases patients instead access the ED. """
categories = [
    "Population Health",
    "Infrastructure"
]
authors = [
    "Jessica McQuade"
]
version = "0.1.0"
fred_versions = [
  ">=8.4",
  "<9"
]

[run_options]
src_dir = "source"
entrypoint = "model/main.fred"