name: Build manifest file

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-manifest:
    name: Build Manifest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build manifest file
        run: sh generate-manifest.sh
      
      - name: Clear S3
        run: aws s3 rm s3://model-library-assets --recursive

      - name: Copy manifest file to S3
        run: aws s3 cp manifest.toml s3://model-library-assets
      
      - name: Copy all images and fred.toml files to S3
        run: aws s3 cp . s3://model-library-assets --recursive --exclude "*" --include "*/*.png" --include "*/*.jpg" --include "*/fred.toml"
